### ISSUE TITLE
How to run the clock face on a Lenovo Smart Clock

### ISSUE THREAD

**Issue by robinbonnes** [flutter/flutter_clock#25] opened 2019-11-28 08:59 UTC
Is there any documentation available how to run the clock face on a Lenovo Smart Clock or any other smart clock?

**Comment by janstol** [comment] 2019-11-29 19:22
Duplicate of #13

**Comment by robinbonnes** [comment] 2019-11-29 22:03
But if its not possible to get the clock face on the clock, why this competition even is there?

**Comment by ride4sun** [comment] 2019-12-01 04:41
I have the clock and would like to try it during programming it. What is the point otherwise?

**Comment by jkurtw** [comment] 2019-12-02 22:32
Yes, this is Duplicate of #13.

However, from flutter.dev/clock, "Some of the clock contest submissions might be integrated into the Lenovo Smart Clock's lineup of clock faces, or used as inspiration for future clock faces!"

**Closed as completed by jkurtw** 2019-12-02 22:32 UTC

**Comment by ride4sun** [comment] 2019-12-02 22:50
Sorry that was starting out great but if I can not even run my own code on
the device that is really stupid Google.
