### ISSUE TITLE
you must share this with Google

### ISSUE THREAD

**Issue by parthpitorda** [flutter/flutter_clock#60] opened 2020-01-07 14:40 UTC
can anyone give me google github id that i can share/Collaborators my repository with google

**Comment by JonathanMonga** [comment] 2020-01-08 14:36
Put your code on github and share that with Google...

**Comment by SirusCodes** [comment] 2020-01-08 19:26
Duplicate of #59

**Comment by SirusCodes** [comment] 2020-01-08 19:29
you need to submit your code from google forms(link given on flutter.dev/clock) and your project should be public on github.

**Comment by parthpitorda** [comment] 2020-01-09 06:07
> Put your code on github and share that with Google...

when i try to share my code with google in github then there is 6 google user name that's why i am asking in which google user id to share code

**Comment by parthpitorda** [comment] 2020-01-09 06:08
> you need to submit your code from google forms(link given on flutter.dev/clock) and your project should be public on

**Comment by Adarsh-Mohanty** [comment] 2020-01-12 18:19
Whom to be added as a collaborator. So much confusion.

**Comment by parthpitorda** [comment] 2020-01-13 08:01
> Whom to be added as a collaborator. So much confusion.

Yes,
please anyone guide us for same

**Comment by parthpitorda** [comment] 2020-01-13 08:01
> Put your code on github and share that with Google...

but with which id??

**Comment by SirusCodes** [comment] 2020-01-13 20:26
> > Put your code on github and share that with Google...
> 
> but with which id??

uk what open this link https://forms.gle/STgU9QMTJLtFjQZE7 this is only place where you need to submit your project

**Comment by SirusCodes** [comment] 2020-01-13 20:27
> Whom to be added as a collaborator. So much confusion.

You are only going to make your project so no need to add any collaborator

**Comment by mitjag** [comment] 2020-01-14 19:32
Submitting requirements are as follows (parts from Flutter Clock Official Rules):

- Before the end of the Contest Period at 11:59:59 P.M. PT on January 20th, 2020, your Submission must be submitted via this Google Form as a ZIP file containing all executable content needed to run the code on a target Android or iOS device.

- Before 11:59 P.M. PT on February 5th, 2020, your Submission must be made public by being hosted on GitHub (https://github.com/) under an appropriate open source license. Your Submission can remain private during the Contest Period.

**Comment by jkurtw** [comment] 2020-01-16 17:57
You don't need to add Google as a collaborator. The requirement is to make your repo _public_ after the submission cut off time:
- _Before 11:59 P.M. PT on February 5th, 2020, your Submission must be made public by being hosted on GitHub (https://github.com/) under an appropriate open source license. Your Submission can remain private during the Contest Period._

We did not ask you to make it public during the competition, so that your code remains private.

**Closed as completed by jkurtw** 2020-01-16 17:57 UTC
